@url_dev=http://localhost:8000/v1/api/

### login
POST {{url_dev}}shop/login
Content-Type: application/json
x-api-key: 3364bf4b357ae34149cf024ba0bbd17a34c2599a0227576106d898794f846fc5dda3f492e5e877ba7f51c91d1b376a7c4f26c19167e5c8091b380a43b8f2a4e7

{
    "email" : "string@gmail.com",
    "password": "1q2w3E*"
}

### signup
POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: 3364bf4b357ae34149cf024ba0bbd17a34c2599a0227576106d898794f846fc5dda3f492e5e877ba7f51c91d1b376a7c4f26c19167e5c8091b380a43b8f2a4e7

{
    "name": "Lê Quốc Anh",
    "email" : "string@gmail.com",
    "password": "1q2w3E*"
}

### logout
POST {{url_dev}}shop/logout
Content-Type: application/json
x-api-key: 3364bf4b357ae34149cf024ba0bbd17a34c2599a0227576106d898794f846fc5dda3f492e5e877ba7f51c91d1b376a7c4f26c19167e5c8091b380a43b8f2a4e7
x-client-id: 661b3d62dd0ac5d0bd4dda73
AUTHORIZATION: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFiM2Q2MmRkMGFjNWQwYmQ0ZGRhNzMiLCJlbWFpbCI6InN0cmluZ0BnbWFpbC5jb20iLCJpYXQiOjE3MTMwOTk2OTcsImV4cCI6MTcxMzA5OTcwN30.at-Ok9CkQ7m1pDuMmH0A6ZbHctubyy4xJOQWDitfvfk

### HandlerRefreshToken 
POST {{url_dev}}shop/handleRefreshToken
Content-Type: application/json
x-api-key: 3364bf4b357ae34149cf024ba0bbd17a34c2599a0227576106d898794f846fc5dda3f492e5e877ba7f51c91d1b376a7c4f26c19167e5c8091b380a43b8f2a4e7
x-client-id: 661b3d62dd0ac5d0bd4dda73
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFiM2Q2MmRkMGFjNWQwYmQ0ZGRhNzMiLCJlbWFpbCI6InN0cmluZ0BnbWFpbC5jb20iLCJpYXQiOjE3MTMzNDUzOTcsImV4cCI6MTcxMzk1MDE5N30.oITazZbYWnlNgUm2yLbrI4RGCnScQAkxm6HsQJYlGto

### Create Product / change product_attributes with same type
POST {{url_dev}}product
Content-Type: application/json
x-api-key: 3364bf4b357ae34149cf024ba0bbd17a34c2599a0227576106d898794f846fc5dda3f492e5e877ba7f51c91d1b376a7c4f26c19167e5c8091b380a43b8f2a4e7
x-client-id: 661b3d62dd0ac5d0bd4dda73
AUTHORIZATION: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFiM2Q2MmRkMGFjNWQwYmQ0ZGRhNzMiLCJlbWFpbCI6InN0cmluZ0BnbWFpbC5jb20iLCJpYXQiOjE3MTM1OTMyMzEsImV4cCI6MTcxMzc2NjAzMX0.fbv2Kl8SD-_H4iFgBJw2yHuqU2dNpCcnUlkKB5m4B6o

{
    "product_name": "^You and Me",
    "product_thumb": "Jennie",
    "product_description": "Jennie",
    "product_price": "1000",
    "product_quantity": "4",
    "product_type": "Furniture",
    "product_attributes": {
        "barnd": "Jennie",
        "size": "Jennie",
        "material": "Jennie"
    }
}

### Publish Product
PUT  {{url_dev}}product/publish/66235f05633f4ae000d6dfd4
Content-Type: application/json
x-api-key: 3364bf4b357ae34149cf024ba0bbd17a34c2599a0227576106d898794f846fc5dda3f492e5e877ba7f51c91d1b376a7c4f26c19167e5c8091b380a43b8f2a4e7
x-client-id: 661b3d62dd0ac5d0bd4dda73
AUTHORIZATION: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFiM2Q2MmRkMGFjNWQwYmQ0ZGRhNzMiLCJlbWFpbCI6InN0cmluZ0BnbWFpbC5jb20iLCJpYXQiOjE3MTM1OTMyMzEsImV4cCI6MTcxMzc2NjAzMX0.fbv2Kl8SD-_H4iFgBJw2yHuqU2dNpCcnUlkKB5m4B6o

### Unpublish Product
PUT  {{url_dev}}product/unpublish/66235f05633f4ae000d6dfd4
Content-Type: application/json
x-api-key: 3364bf4b357ae34149cf024ba0bbd17a34c2599a0227576106d898794f846fc5dda3f492e5e877ba7f51c91d1b376a7c4f26c19167e5c8091b380a43b8f2a4e7
x-client-id: 661b3d62dd0ac5d0bd4dda73
AUTHORIZATION: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFiM2Q2MmRkMGFjNWQwYmQ0ZGRhNzMiLCJlbWFpbCI6InN0cmluZ0BnbWFpbC5jb20iLCJpYXQiOjE3MTM1OTMyMzEsImV4cCI6MTcxMzc2NjAzMX0.fbv2Kl8SD-_H4iFgBJw2yHuqU2dNpCcnUlkKB5m4B6o



### Get All Draft Product For Shop  
GET  {{url_dev}}product/isDraft
Content-Type: application/json
x-api-key: 3364bf4b357ae34149cf024ba0bbd17a34c2599a0227576106d898794f846fc5dda3f492e5e877ba7f51c91d1b376a7c4f26c19167e5c8091b380a43b8f2a4e7
x-client-id: 661b3d62dd0ac5d0bd4dda73
AUTHORIZATION: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFiM2Q2MmRkMGFjNWQwYmQ0ZGRhNzMiLCJlbWFpbCI6InN0cmluZ0BnbWFpbC5jb20iLCJpYXQiOjE3MTM1OTMyMzEsImV4cCI6MTcxMzc2NjAzMX0.fbv2Kl8SD-_H4iFgBJw2yHuqU2dNpCcnUlkKB5m4B6o

### Get All Published Product For Shop  
GET  {{url_dev}}product/published
Content-Type: application/json
x-api-key: 3364bf4b357ae34149cf024ba0bbd17a34c2599a0227576106d898794f846fc5dda3f492e5e877ba7f51c91d1b376a7c4f26c19167e5c8091b380a43b8f2a4e7
x-client-id: 661b3d62dd0ac5d0bd4dda73
AUTHORIZATION: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFiM2Q2MmRkMGFjNWQwYmQ0ZGRhNzMiLCJlbWFpbCI6InN0cmluZ0BnbWFpbC5jb20iLCJpYXQiOjE3MTM1OTMyMzEsImV4cCI6MTcxMzc2NjAzMX0.fbv2Kl8SD-_H4iFgBJw2yHuqU2dNpCcnUlkKB5m4B6o

